### ISSUE TITLE
Mask RCNN

### ISSUE THREAD

**Issue by yyfyan** [WenqiangX/ese_seg#1]
hello, best job.
I noted Mask RCNN achieved 68.5 mAP on the VOC12 val set, how train the Mask RCNN on the VOC dataset? the train set including SBD+VOC12?

**Comment by WenqiangX** [comment]
Hi, VOC 2012 val set is used for validation, training including sbd + voc12. It is a common practice since SDS.

**Comment by yyfyan** [comment]
Thanks. 
the training set size is 10582? @WenqiangX

**Comment by WenqiangX** [comment]
@yyfyan no the training set from sbd is http://home.bharathh.info/pubs/codes/SBD/train_noval.txt, this will exclude all the val in voc2012. The default train/val split will contain ~500 voc2012 val images in train split.
