### ISSUE TITLE
Inner center

### ISSUE THREAD

**Issue by alexandre01** [WenqiangX/ese_seg#2]
Hi, congrats for the awesome work! Could you just explain how to compute the inner center given a segmentation mask? The centerdot function doesn't seem to output the correct point as shown in the paper. Thanks in advance.

![inner_center](https://user-images.githubusercontent.com/16474636/63691340-34f44880-c80f-11e9-8473-2a41c3a78a52.png)

**Comment by alexandre01** [comment]
Also tried it using the preprocessing output of label_centerdeg. The point is different, but still not truly inside the segmentation mask. Thanks for your help.

![inner_center_2](https://user-images.githubusercontent.com/16474636/63692455-fca23980-c811-11e9-8f43-34de7a7ac937.png)

**Comment by Haiyang-W** [comment]
> Also tried it using the preprocessing output of label_centerdeg. The point is different, but still not truly inside the segmentation mask. Thanks for your help.
> 
> ![inner_center_2](https://user-images.githubusercontent.com/16474636/63692455-fca23980-c811-11e9-8f43-34de7a7ac937.png)

The paper is the most-far way, and this code is implemented as most-close way. We find how to define the inner center dot is not an important thing for the final result. Just make sure it's inside the mask.

**Comment by alexandre01** [comment]
Okay that works. Thanks for your response!
